package com.example.fifiaopenapi.api;

public class Apikey {
    public static final String API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJYLUFwcC1SYXRlLUxpbWl0IjoiNTAwOjEwIiwiYWNjb3VudF9pZCI6IjE4MjkwMDExNjgiLCJhdXRoX2lkIjoiMiIsImV4cCI6MTY3NjM5MTY1NiwiaWF0IjoxNjYwODM5NjU2LCJuYmYiOjE2NjA4Mzk2NTYsInNlcnZpY2VfaWQiOiI0MzAwMTE0ODEiLCJ0b2tlbl90eXBlIjoiQWNjZXNzVG9rZW4ifQ.oH8CQoXOb_-UdrNA-sGkbLoTKiNst27wgv1Ej6ceAss";
}
